name: rentall
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  firebase_storage: ^10.2.9
  easy_localization: ^3.0.0
  cached_network_image: ^3.2.0
  flutter_form_builder: ^7.1.1
  image_picker: ^0.8.4+11
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
